name: MAME-libretro Linux x86_64

on:
  push:
    branches:
      - master

jobs:
  Linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt install build-essential mesa-common-dev binutils
    - run: make -f Makefile.libretro -j8
    - run: strip -s mame_libretro.so
    - run: zip -9 mame_libretro.so.zip mame_libretro.so
    - name: Upload MAME core
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: Linux_64-bit
        prerelease: false
        title: Linux x86_64
        files: |
          mame_libretro.so.zip
    - name: Save core for upload job
      uses: actions/upload-artifact@v2
      with:
        name: mame_libretro.so.zip
        path: mame_libretro.so.zip
  
  uploadToBB:
    name: Upload core to buildbot
    runs-on: ubuntu-latest
    needs: Linux
    
    steps:
    - name: Recover core from artifacts
      uses: actions/download-artifact@v2
      with:
        name: mame_libretro.so.zip
        path: .
    - name: Upload to buildbot
      id: deploy
      uses: Pendect/action-rsyncer@v1.1.0
      env:
        DEPLOY_KEY: ${{ secrets.KEY }}
      with:
        flags: '-vazr --delete'
        options: ''
        ssh_options: '-p ${{ secrets.PORT }}'
        src: mame_libretro.so.zip
        dest: '${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ secrets.LINUX_X86_64_PATH }}'

