name: MAME-libretro macOS x86_64

on:
  push:
    branches:
      - master

jobs:
  macOS:
    name: Build for macOS
    runs-on: macos-latest
    
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Build libretro mame core
      run: |
        touch mame_libretro.dylib
        zip -9 mame_libretro.zip mame_libretro.dylib
    - name: Create new release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: macOS-x86_64
        prerelease: false
        title: macOS x86_64
        files: |
          mame_libretro.zip
    - name: Save core for upload job
      uses: actions/upload-artifact@v2
      with:
        name: mame_libretro.zip
        path: mame_libretro.zip

  uploadToBB:
    name: Upload core to buildbot
    runs-on: ubuntu-latest
    needs: macOS
    
    steps:
    - name: Recover core from artifacts
      uses: actions/download-artifact@v2
      with:
        name: mame_libretro.zip
        path: .
    - name: Upload to buildbot
      uses: trendyminds/github-actions-rsync@master
      with:
        RSYNC_OPTIONS: -avzr --delete -p ${{ secrets.PORT }}
        RSYNC_TARGET: ${{ secrets.MACOS_X86_64_PATH }}
        RSYNC_SOURCE: /mame_libretro.zip
      env:
        SSH_PRIVATE_KEY: ${{secrets.KEY}}
        SSH_USERNAME: ${{secrets.USERNAME}}
        SSH_HOSTNAME: ${{secrets.HOST}}


