name: MAME-libretro Windows x86_64

on:
  push:
    branches:
      - master

jobs:
  Windows:
    name: Build for Windows
    runs-on: windows-latest

    steps:
    - uses: numworks/setup-msys2@v1
      with:
        msystem: MINGW64
    - run: msys2do pacman -S --noconfirm --disable-download-timeout --needed wget git make mingw-w64-x86_64-binutils mingw-w64-x86_64-toolchain mingw-w64-x86_64-zlib mingw-w64-x86_64-pkg-config mingw-w64-x86_64-python2 zip p7zip
    - uses: actions/checkout@v2
    - run: msys2do make -f Makefile.libretro -j8
    - run: strip.exe -s mame_libretro.dll
    - run: msys2do zip -9 mame_libretro.zip mame_libretro.dll
    - name: Upload MAME core
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: Windows_64-bit
        prerelease: false
        title: Windows x86_64
        files: |
          mame_libretro.zip
    - name: Save core for upload job
      uses: actions/upload-artifact@v2
      with:
        name: mame_libretro.zip
        path: mame_libretro.zip
  
  uploadToBB:
    name: Upload core to buildbot
    runs-on: ubuntu-latest
    needs: Windows
    
    steps:
    - name: Recover core from artifacts
      uses: actions/download-artifact@v2
      with:
        name: mame_libretro.zip
        path: .
    - name: Upload to buildbot
      id: deploy
      uses: Pendect/action-rsyncer@v1.1.0
      env:
        DEPLOY_KEY: ${{ secrets.KEY }}
      with:
        flags: '-vazr --delete'
        options: ''
        ssh_options: '-p ${{ secrets.PORT }}'
        src: mame_libretro.zip
        dest: '${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ secrets.WINDOWS_X86_64_PATH }}'


